services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: spring-ai-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgresml
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myappuser -d postgresml"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local 